name: Dependabot auto-merge
on:
  pull_request:
    types: [opened]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Enhanced security: Verify both the user login and repository to prevent impersonation attacks
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'MasatoMakino/threejs-billboard'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: |
          (
            steps.metadata.outputs.dependency-type == 'direct:development' &&
            steps.metadata.outputs.update-type == 'version-update:semver-patch'
          ) || (
            steps.metadata.outputs.dependency-type == 'direct:production' &&
            steps.metadata.outputs.update-type == 'version-update:semver-patch'
          ) || (
            steps.metadata.outputs.dependency-type == 'indirect' &&
            steps.metadata.outputs.update-type == 'version-update:semver-patch'
          ) || (
            steps.metadata.outputs.dependency-type == 'direct:development' &&
            steps.metadata.outputs.update-type == 'version-update:semver-minor' &&
            steps.metadata.outputs.previous-version != '' &&
            startsWith(steps.metadata.outputs.previous-version, '0.') == false
          )
        # Security: Use @dependabot command instead of direct gh pr merge for enhanced validation
        run: gh pr comment "$PR_URL" --body "@dependabot squash and merge"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
