name: Publish to NPM
on:
  release:
    types: [published]
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Required for repository access
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Use Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: "20"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: Upgrade npm to latest
        run: npm install -g npm@latest
      - run: npm ci
      - name: build binary
        run: npm run buildTS
      - name: Publish package on NPM 📦
        run: npm publish --access public
